### ISSUE TITLE
loading script/403 error on some browsers for category-filters.js - missing "load more" button

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-news-theme#13] opened 2018-12-03 18:42 UTC
## Problem

Loading news.littlesis.org fails to show the "load more" button on some browsers.  

Reported to occur on 
  -  Firefox 64.0b11
  -  Google Chrome Version 70.0.3538.67

This error is printed onto the console:
```
Loading failed for the <script> with source “https://news.littlesis.org/wp-content/themes/littlesis/js/category-filters.js”. news.littlesis.org:729:1 
```

These browsers don't seem to have the same issue:
  - Firefox 62.0 
  - Chromium Version 70.0.3538.67

## Details

By navigating to  ``` https://news.littlesis.org/wp-content/themes/littlesis/js/category-filters.js ``` you can reproduce the problem in affected browsers. On some browsers it shows up correctly, but on others it displays a 403 message.

On Firefox 64, this message is sent to the console:
```
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.
```

**Comment by misfist** [comment] 2018-12-03 22:41
This is a strange and inconsistent problem...

On one laptop, I can't reproduce

* Firefox 63.0.3 (64-bit)
* Chrome Version 70.0.3538.110 (Official Build) (64-bit)

On another laptop, I can reproduce

* Firefox 63.0.3 (64-bit)
* Chrome Version 70.0.3538.110 (Official Build) (64-bit)

I'd like to have a look at the file permissions for that file, but I don't have access.

**Comment by aepyornis** [comment] 2018-12-05 15:22
Yeah! it's a weird one. I'm guessing it has to do with a character encoding header -- since that's something where the browser interacts with the laptop setting? I find it odd that the same browser version has a different result on different laptops.

**Comment by misfist** [comment] 2018-12-05 16:13
The character encoding header is present on the page and other js files are being loaded without a problem. There seems to be something particular about this file. 

>  I find it odd that the same browser version has a different result on different laptops.

Yes, very odd. The one that failed to load had 2 primary differences (that I can think of): 

1. Newer version of Ubuntu (18.04 vs 16.04)
2. Accessing the internet over wif-fi rather than wired connection

**Comment by aepyornis** [comment] 2018-12-05 17:20
I think I've fixed it now.  It was simply that there were wrong permission wp-content.

I think the only reason (at least on my computer) why some browsers worked had to do with caching (either locally or on the CDN)

I `chown`'d the  whole directory with user `wordpress` and importantly with group ` www-data`

**Comment by misfist** [comment] 2018-12-05 19:06
> I chown'd the whole directory with user wordpress and importantly with group www-data

OK. What permissions did you give the directory? Just want to verify that they are correct for uploading images, which are stored in `wp-content/uploads`

**Comment by misfist** [comment] 2018-12-07 18:20
Once this is verified, let's close this.

**Closed by misfist** 2018-12-07 18:20 UTC
